<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yulgnier</groupId>
        <artifactId>for-yourself</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>com.yulgnier.gateway</groupId>
    <artifactId>for-yourself-gateway</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- 1. Spring Cloud Gateway 核心依赖（必须） -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>

        <!-- 2. Nacos 服务发现（让网关找到其他微服务） -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- 3. Nacos 配置中心（后续存路由规则用） -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- 4. 加载 bootstrap 配置文件（必须加，否则nacos配置不生效） -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>

    </dependencies>


</project>