server:
  port: ${your.server.port}

# 全局时间格式化（统一后端返回时间格式）
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: ${your.timezone}

spring:
  profiles:
    active: local           #TODO-----------------------改---------------------

  # 邮箱配置（项目专用发件邮箱）
  mail:
    host: ${your.mail.host}  # 邮箱服务器地址
    username: ${your.mail.username}  # 邮箱账号
    password: ${your.mail.password}  # 邮箱授权码
    default-encoding: utf-8
    protocol: smtp    # 邮箱协议
    properties:
      mail:
        debug: ${your.mail.debug}   # 是否强制输出日志信息
        ssl:
          enable: true  # 开启SSL

# 日志配置（对应logback-spring.xml里的LOG_PATH）
logging:
  level:
    #✅ 你的业务代码包：设为DEBUG
    # 把 com.yourproject 改成你项目的**根包名**（启动类所在的包）
    com.yulgnier.center.admin.user: DEBUG            #TODO-----------------------改---------------------
    com.yulgnier.common: DEBUG  # 公共模块（包含全局异常处理器）  #TODO-----------------------改---------------------
  file:
    path: ${your.logging.file.path}

cloudflare:
  turnstile:
    secret: ${your.cloudflare.turnstile.secret}

# JWT 配置
jwt:
  secret-key: ${your.jwt.secret-key}
  issuer: ${your.jwt.issuer}
  expire-hour: ${your.jwt.expire-hour}

# 雪花算法分布式配置（每个实例改这里就行）
snowflake:
  data-center-id: ${your.snowflake.data-center-id}    # 数据中心ID 0~31
  worker-id: ${your.snowflake.worker-id}         # 机器ID 0~31

gateway:
  white-list:
    # Knife4j 接口文档
    - /doc.html
    - /webjars/**
    - /swagger-resources/**
    - /v3/api-docs/**
    - /v2/api-docs/**
    # 浏览器自动请求 + 框架错误页
    - /.well-known/**
    - /error
    - /favicon.ico
    # 项目用
    - /center-common/user/register
    - /center-common/user/login
    - /center-common/user/getEmailCode
    - /center-common/user/forgetPassword

truth:
  truth-key: ${your.truth.truth-key}
  truth-value: ${your.truth.truth-value}


yulgnier:
  email-expire-minutes: ${your.yulgnier.email-expire-minutes}
  email-try-times: ${your.yulgnier.email-try-times}  # 邮箱验证码尝试次数